# config/enhanced_yolo_config.yaml
# 增强版YOLO检测器配置文件

yolo_detector:
  ros__parameters:
    # 模型配置
    model_path: "/home/ubuntu/robot_ws/src/robot_visioner/models/best.pt"          # 分割模型路径
    device: "cuda"                        # 设备: cpu 或 cuda
    confidence_threshold: 0.5             # 检测置信度阈值
    iou_threshold: 0.4                    # NMS IoU阈值
    max_detections: 100                   # 最大检测数量
    agnostic_nms: false                   # 类别无关的NMS
    
    # 输入输出话题
    input_topic: "/camera/color/image_raw"
    camera_info_topic: "/camera/color/camera_info"
    output_detection_topic: "/yolo/detection_result"     # 检测结果（只有边界框）
    output_mask_topic: "/yolo/mask"                      # 分割mask（二值图像）
    output_combined_topic: "/yolo/combined_result"       # 合并结果（检测+分割）
    
    # 分割功能配置
    enable_segmentation: true             # 是否启用分割功能
    mask_threshold: 0.5                   # mask二值化阈值
    target_classes: []                    # 目标类别列表，空列表=所有类别
    # target_classes: [0, 1, 2, 5, 7]    # 示例：person, bicycle, car, bus, truck
    publish_individual_masks: false       # 是否发布单独的类别mask（未来功能）
    
    # 图像参数
    image_width: 640
    image_height: 480
    
    # 性能调优
    processing_rate: 30.0                 # 期望处理帧率
    queue_size: 10                        # 话题队列大小

# 特定场景配置示例
robot_visioner_integration:
  ros__parameters:
    # 与robot_visioner节点的集成配置
    depth_topic: "/camera/depth/image_raw"
    camera_info_topic: "/camera/camera_info"
    mask_input_topic: "/yolo/mask"        # 来自YOLO的mask
    pointcloud_output_topic: "/extracted_pointcloud"
    
    # 坐标系配置
    frame_id: "camera_link"
    
    # 处理同步
    sync_tolerance: 0.05                  # 时间同步容差（秒）

# 不同应用场景的预设配置
presets:
  # 高精度配置（较慢但更准确）
  high_accuracy:
    confidence_threshold: 0.7
    iou_threshold: 0.3
    mask_threshold: 0.6
    enable_segmentation: true
    max_detections: 50
    
  # 高速度配置（更快但可能不够准确）  
  high_speed:
    confidence_threshold: 0.4
    iou_threshold: 0.5
    mask_threshold: 0.4
    enable_segmentation: false  # 禁用分割以提高速度
    max_detections: 20
    
  # 机器人抓取配置
  robot_grasping:
    confidence_threshold: 0.6
    target_classes: [0, 39, 40, 41, 42, 43, 44, 46, 47]  # 人和各种物体
    enable_segmentation: true
    mask_threshold: 0.5
    
  # 导航避障配置
  navigation:
    confidence_threshold: 0.5
    target_classes: [0, 1, 2, 3, 5, 7]  # 人、车辆等移动障碍物
    enable_segmentation: false
    max_detections: 30

# COCO类别映射（参考）
coco_classes:
  0: "person"
  1: "bicycle" 
  2: "car"
  3: "motorcycle"
  5: "bus"
  7: "truck"
  39: "bottle"
  40: "wine glass"
  41: "cup"
  42: "fork"
  43: "knife"
  44: "spoon"
  46: "banana"
  47: "apple"
  # ... 更多类别