# config/robot_visioner_config.yaml
# Robot Visioner 节点配置文件

robot_visioner:
  ros__parameters:
    # 话题配置
    depth_topic: "/camera/depth/image_raw"
    mask_topic: "/yolo/mask" 
    camera_info_topic: "/camera/camera_info"
    output_topic: "/extracted_pointcloud"
    
    # 处理参数
    depth_scale: 1000.0              # 深度缩放因子 (mm -> m)
    mask_threshold: 128              # Mask二值化阈值 (0-255)
    sync_tolerance: 0.05             # 时间同步容差 (秒)
    
    # 聚类分析参数
    enable_clustering: true          # 是否启用聚类
    cluster_tolerance: 0.02          # 聚类容差 (米)
    min_cluster_size: 100            # 最小聚类大小 (点数)
    max_cluster_size: 25000          # 最大聚类大小 (点数)
    
    # 点云过滤参数
    enable_voxel_filter: true        # 是否启用体素滤波
    voxel_leaf_size: 0.01            # 体素大小 (米)
    enable_outlier_filter: true      # 是否启用离群点过滤
    outlier_mean_k: 50               # 离群点检测邻域点数
    outlier_stddev_mul: 1.0          # 离群点标准差倍数
    
    # 工作空间限制 (米)
    workspace_x_min: -2.0
    workspace_x_max: 2.0
    workspace_y_min: -2.0  
    workspace_y_max: 2.0
    workspace_z_min: 0.1
    workspace_z_max: 3.0
    
    # 可视化参数
    marker_scale: 0.05               # 标记大小 (米)
    frame_id: "camera_link"          # 参考坐标系
    
    # 性能参数
    processing_rate: 10.0            # 处理频率 (Hz)
    
# YOLO分割节点配置
yolo_segmentation:
  ros__parameters:
    model_path: "yolov8n-seg.pt"
    confidence_threshold: 0.5
    iou_threshold: 0.5
    target_classes: []               # 空列表表示检测所有类别
    # target_classes: [0, 1, 2]     # 示例：只检测person, bicycle, car
    
    # 输入输出话题
    input_topic: "/camera/image_raw"
    output_mask_topic: "/yolo/mask"
    output_result_topic: "/yolo/segmentation_result"
    
    # 处理参数
    max_detections: 100
    mask_threshold: 0.5

# 相机配置（参考）
camera_config:
  ros__parameters:
    # Intel RealSense D435 示例参数
    image_width: 640
    image_height: 480
    depth_width: 640
    depth_height: 480
    
    # 内参矩阵 (示例值，需要根据实际相机标定)
    camera_matrix: [615.0, 0.0, 320.0,
                   0.0, 615.0, 240.0, 
                   0.0, 0.0, 1.0]
    
    # 畸变系数
    distortion_coefficients: [0.0, 0.0, 0.0, 0.0, 0.0]
    
    # 深度相关参数
    depth_scale: 0.001               # 深度单位转换 (mm -> m)
    min_depth: 0.1                   # 最小有效深度 (m)
    max_depth: 10.0                  # 最大有效深度 (m)