robot_visioner:
  ros__parameters:
    # 话题配置（支持彩色点云）
    rgb_topic: "/camera/color/image_raw"            # RGB图像话题（新增）
    depth_topic: "/camera/depth/image_raw"          # 深度图像话题
    mask_topic: "/yolo/mask"                        # 来自YOLO的分割mask话题
    camera_info_topic: "/camera/depth/camera_info"  # 深度相机信息话题
    output_topic: "/extracted_pointcloud"           # 输出彩色点云话题
    
    # 处理参数
    depth_scale: 1000.0              # 深度缩放因子 (mm -> m)
    mask_threshold: 128              # Mask二值化阈值 (0-255)
    sync_tolerance: 0.05             # 时间同步容差 (秒)
    enable_rgb_color: true           # 是否启用RGB真彩色（新增）
    
    # 聚类分析参数
    enable_clustering: true          # 是否启用聚类
    cluster_tolerance: 0.02          # 聚类容差 (米)
    min_cluster_size: 30            # 最小聚类大小 (点数)
    max_cluster_size: 25000          # 最大聚类大小 (点数)
    
    # 点云过滤参数
    enable_voxel_filter: true        # 是否启用体素滤波
    voxel_leaf_size: 0.008           # 体素大小 (米) - 更精细以保持颜色细节
    enable_outlier_filter: true      # 是否启用离群点过滤
    outlier_mean_k: 30               # 离群点检测邻域点数 - 减少以提高性能
    outlier_stddev_mul: 1.0          # 离群点标准差倍数
    
    # 工作空间限制 (米)
    workspace_x_min: -2.0
    workspace_x_max: 2.0
    workspace_y_min: -2.0  
    workspace_y_max: 2.0
    workspace_z_min: 0.1
    workspace_z_max: 3.0
    
    # 可视化参数
    marker_scale: 0.01               # 标记大小 (米) - 稍大以便观察
    frame_id: "camera_depth_optical_frame"  # 参考坐标系
    
    # 性能参数
    processing_rate: 10.0            # 处理频率 (Hz)
    
    # ROS2参数
    use_sim_time: false              # 是否使用仿真时间
    
    # 输出话题配置
    center_point_topic: "/robot_visioner/center_point"        # 中心点话题
    center_marker_topic: "/robot_visioner/center_marker"      # 中心点标记话题
    cluster_markers_topic: "/robot_visioner/cluster_markers"  # 聚类标记话题